import React from "react";

export interface AIRecommendation {
  id: string;
  action: string; // Backend format
  priority: "critical" | "high" | "medium" | "low"; // Backend format
  description: string;
  reasoning?: string; // Backend format (optional)
  approved?: boolean;
}

interface AIRecommendationsCardProps {
  recommendations: AIRecommendation[];
  onApprove: (id: string) => void;
  onDeny: (id: string) => void;
}

const getPriorityColor = (priority: string) => {
  switch (priority) {
    case "critical":
      return {
        bg: "bg-red-500/20",
        text: "text-red-400",
        border: "border-red-500/30",
      };
    case "high":
      return {
        bg: "bg-orange-500/20",
        text: "text-orange-400",
        border: "border-orange-500/30",
      };
    case "medium":
      return {
        bg: "bg-yellow-500/20",
        text: "text-yellow-400",
        border: "border-yellow-500/30",
      };
    case "low":
      return {
        bg: "bg-blue-500/20",
        text: "text-blue-400",
        border: "border-blue-500/30",
      };
    default:
      return {
        bg: "bg-gray-500/20",
        text: "text-gray-400",
        border: "border-gray-500/30",
      };
  }
};

export const AIRecommendationsCard: React.FC<AIRecommendationsCardProps> = ({
  recommendations,
  onApprove,
  onDeny,
}) => {
  if (!recommendations || recommendations.length === 0) {
    return null;
  }

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-xl p-6">
      <div className="flex items-center gap-2 mb-4">
        <div className="w-8 h-8 bg-gradient-to-br from-cyan-500 to-purple-500 rounded-lg flex items-center justify-center">
          <i className="fas fa-brain text-white text-sm" />
        </div>
        <h3 className="text-lg font-semibold text-white">AI-Powered Recommendations</h3>
        <span className="ml-auto text-xs text-gray-500 bg-slate-950/50 px-2 py-1 rounded">
          <i className="fas fa-robot mr-1" />
          Generated by Google Gemini AI
        </span>
      </div>
      
      <div className="space-y-3">
        {recommendations.map((rec, index) => {
          const colors = getPriorityColor(rec.priority);
          
          return (
            <div
              key={rec.id || index}
              className="bg-slate-950/50 border border-slate-800 rounded-lg p-4 hover:border-slate-700 transition-colors"
            >
              <div className="flex items-start gap-3">
                <div className={`w-8 h-8 ${colors.bg} rounded-lg flex items-center justify-center mt-1 shrink-0`}>
                  <i className={`fas fa-lightbulb ${colors.text} text-sm`} />
                </div>
                
                <div className="flex-1 min-w-0">
                  <div className="flex items-start justify-between gap-2 mb-2">
                    <h4 className="font-medium text-white">{rec.action}</h4>
                    <span className={`px-2 py-1 ${colors.bg} ${colors.text} border ${colors.border} rounded text-xs font-medium uppercase shrink-0`}>
                      {rec.priority}
                    </span>
                  </div>
                  
                  <p className="text-sm text-gray-400 mb-2 leading-relaxed">
                    {rec.description}
                  </p>
                  
                  {rec.reasoning && (
                    <div className="bg-slate-900/50 border border-slate-800 rounded p-2 mb-3">
                      <p className="text-xs text-gray-500">
                        <i className="fas fa-info-circle mr-1 text-cyan-500" />
                        <span className="font-medium text-gray-400">Reasoning:</span> {rec.reasoning}
                      </p>
                    </div>
                  )}
                  
                  <div className="flex items-center gap-2 pt-2 border-t border-slate-800">
                    {rec.approved === undefined ? (
                      <>
                        <button
                          onClick={() => onApprove(rec.id || String(index))}
                          className="px-3 py-1.5 bg-green-500/20 text-green-400 border border-green-500/30 rounded hover:bg-green-500/30 transition-colors text-sm font-medium"
                        >
                          <i className="fas fa-check mr-1.5" />
                          Approve & Execute
                        </button>
                        <button
                          onClick={() => onDeny(rec.id || String(index))}
                          className="px-3 py-1.5 bg-red-500/20 text-red-400 border border-red-500/30 rounded hover:bg-red-500/30 transition-colors text-sm font-medium"
                        >
                          <i className="fas fa-times mr-1.5" />
                          Deny
                        </button>
                      </>
                    ) : rec.approved ? (
                      <span className="px-3 py-1.5 bg-green-500/20 text-green-400 border border-green-500/30 rounded text-sm font-medium">
                        <i className="fas fa-check-circle mr-1.5" />
                        Approved & Executed
                      </span>
                    ) : (
                      <span className="px-3 py-1.5 bg-red-500/20 text-red-400 border border-red-500/30 rounded text-sm font-medium">
                        <i className="fas fa-times-circle mr-1.5" />
                        Denied
                      </span>
                    )}
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>
      
      <div className="mt-4 p-3 bg-cyan-500/10 border border-cyan-500/20 rounded-lg">
        <p className="text-xs text-cyan-300">
          <i className="fas fa-magic-wand-sparkles mr-1.5" />
          These recommendations are AI-generated based on threat intelligence analysis. Review carefully before execution.
        </p>
      </div>
    </div>
  );
};
